name: API Tests with Allure Report

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонуємо репозиторій
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Встановлюємо Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Встановлюємо залежності
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      # 4️⃣ Запускаємо тести з Allure
      - name: Run API tests with Pytest and Allure
        run: |
          pytest tests --alluredir=allure-results

      # 5️⃣ Встановлюєм