name: API Tests with Allure Report

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout репозиторію
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Встановлюємо Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣ Встановлюємо залежності
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      # 4️⃣ Запускаємо тести з Allure
      - name: Run API tests with Pytest and Allure
        run: |
          pytest tests --alluredir=allure-results

      # 5️⃣ Генеруємо Allure HTML Report
      - name: Generate Allure HTML report
        run: |
          mkdir -p allure-report
          allure generate allure-results -o allure-report --clean

      # 6️⃣ Деплой звіту на GitHub Pages (gh-pages branch)
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report
          keep_files: false

      # 7️⃣ Вивід посилання на звіт
      - name: Display report URL
        run: echo "✅ Allure Report: https://olenakravets.github.io/api_tests/"
